Update build steps to avoid removing yum (#842)
Our publish step for the docker container was failing since yum in now a
protected package in the ubi base image.

I've updated the script to leave yum, but clear it's cache. The
resulting image results in a slightly smaller (184MB vs 193MB) image.

From the output logs:

```
error: Could not depsolve transaction; 1 problem detected: Problem: The
operation would result in removing the following protected packages: yum
```